name: Pull Docker Image（mihomo）

on:
  workflow_dispatch:

jobs:
  pull_and_save:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Docker SDK
      run: pip install docker

    - name: Run Python script to pull and save image
      run: python scripts/pull_and_save.py

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: mihomo-image
        path: /tmp/mihomo.tar
