name: Pull Docker Image and Upload

on:
  workflow_dispatch:

jobs:
  pull-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Docker
      uses: docker/setup-buildx-action@v2

    - name: Pull Docker image using Python
      run: python scripts/pull_and_save.py

    - name: Upload image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: mihomo-image
        path: mihomo.tar
