name: Pull Docker Image

on:
  workflow_dispatch:

jobs:
  pull_and_save:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Docker SDK
      run: pip install docker

    - name: Run Python script to pull and save image
      run: python scripts/pull_and_save.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git diff --quiet && git diff --staged --quiet || git commit -m "Update rules: $(date +'%Y-%m-%d %H:%M UTC+8')"
        git push
